### ISSUE TITLE
Say sistemlərində çevirmə ilə bağlı

### ISSUE THREAD

**Issue by nijatjafarov** [Qurbanova/PragmatechFoundationProjects#1]
35 ədədini ikilik say sisteminə düzgün çevirməmisiniz. Çevirmə zamanı qisməti də nəzərə almaq lazımdır. İlk öncə qismət yazılmalı daha sonra tərsdən qalıqlar, yəni 100011. Sizin əldə etdiyiniz (000)11 nəticəsi isə 3 ədədinin ikilik qarşılığıdır.

**Comment by Qurbanova** [comment]
Salam. Çox sağolun, sonuncu qisməti qeyd etməyi unutmuşam.

**Comment by nijatjafarov** [comment]
Aydındır, buyurun. Dünənki tapşırıqlarda da problem görmədiyim üçün əlavə issue açmadım və yəqin bügünün də tapşırıqlarını yaxın zamanda edərsiniz. Əlavə sualınız yoxdursa "close issue" edə bilərsiniz.
